### ISSUE TITLE
TODO for mid report 

### ISSUE THREAD

**Issue by kunal-iitj** [kunal-iitj/Inter-IIT-Project#9]
- [x] Make README for both the backend and the main website
- [x]  Make report 
- [x] Finish Login and Sign-Up page along with backend
- [x] Finish all the frontend pages along with routing.

**Comment by kunal-iitj** [comment]
Completed all these tasks
